# Generated by Django 5.2.5 on 2026-05-27 03:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragbot', '0002_pgvector_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('folder_name', models.CharField(blank=True, max_length=512)),
                ('page_token', models.CharField(blank=True, max_length=1024)),
                ('folder_fingerprint', models.CharField(blank=True, max_length=64)),
                ('pending_file_ids', models.JSONField(default=list)),
                ('debounce_seconds', models.PositiveIntegerField(default=600)),
                ('last_change_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('is_indexing', models.BooleanField(default=False)),
                ('indexing_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Drive Sync State',
            },
        ),
        migrations.CreateModel(
            name='DriveSyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(choices=[('webhook', 'Webhook received'), ('check', 'Scheduled check'), ('index_start', 'Index started'), ('index_done', 'Index completed'), ('index_skip', 'Index skipped (no changes)'), ('index_fail', 'Index failed'), ('debounce', 'Skipped (debounce active)'), ('lock_busy', 'Skipped (lock held)')], max_length=20)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='indexversion',
            name='unique_folder_version',
        ),
        migrations.RenameIndex(
            model_name='documentchunk',
            new_name='ragbot_docu_version_735c11_idx',
            old_name='idx_chunk_version',
        ),
        migrations.RenameIndex(
            model_name='documentchunk',
            new_name='ragbot_docu_documen_f9d2a7_idx',
            old_name='idx_chunk_doc_order',
        ),
        migrations.RenameIndex(
            model_name='indexversion',
            new_name='ragbot_inde_folder__cc9d7a_idx',
            old_name='idx_folder_active',
        ),
        migrations.RenameIndex(
            model_name='sourcedocument',
            new_name='ragbot_sour_version_5f2f6e_idx',
            old_name='idx_doc_version_file',
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='indexversion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sourcedocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='indexversion',
            unique_together={('folder_id', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='drivesyncevent',
            index=models.Index(fields=['folder_id', 'event_type'], name='ragbot_driv_folder__ea1939_idx'),
        ),
    ]
