# Generated by Django 5.2.5 on 2026-06-09 05:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragbot', '0005_conversation_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_url', models.URLField(db_index=True, max_length=2048, unique=True)),
                ('label', models.CharField(blank=True, help_text="Human-friendly name, e.g. 'NSW Regs 2011-0653'", max_length=255)),
                ('folder_id', models.CharField(help_text="Logical folder_id used in IndexVersion — e.g. 'web:nsw-regs-0653'", max_length=255)),
                ('content_fingerprint', models.CharField(blank=True, max_length=64)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('is_indexing', models.BooleanField(default=False)),
                ('indexing_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Web Sync State',
            },
        ),
    ]
