# Generated by Django 5.2.5 on 2026-06-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragbot', '0006_websyncstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedocument',
            name='source_type',
            field=models.CharField(choices=[('drive', 'Google Drive'), ('web', 'Web')], default='drive', max_length=10),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='source_url',
            field=models.URLField(blank=True, help_text='Drive share URL or scraped page URL', max_length=2048),
        ),
    ]
