# Generated by Django 5.2.5 on 2026-07-02 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragbot', '0007_sourcedocument_source_type_sourcedocument_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedocument',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The page whose crawl discovered this URL (web sources only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ragbot.sourcedocument'),
        ),
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['version', 'parent'], name='ragbot_sour_version_aaea40_idx'),
        ),
    ]
