# Generated by Django 5.2.5 on 2026-07-03 13:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragbot', '0008_source_document_model_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=2048, unique=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('last_scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_version', models.ForeignKey(blank=True, help_text='The version this URL was last indexed into', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ragbot.indexversion')),
            ],
            options={
                'verbose_name': 'Scraped URL Cache',
            },
        ),
    ]
