# Generated by Django 5.2.5 on 2026-07-07 03:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragbot', '0009_recording_visitred_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='NightlyBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='The calendar date this bundle was created for (midnight run date)', unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='True for the currently serving bundle')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('versions', models.ManyToManyField(blank=True, help_text='All IndexVersions (any status) created during this nightly run', related_name='bundles', to='ragbot.indexversion')),
            ],
            options={
                'verbose_name': 'Nightly Bundle',
                'verbose_name_plural': 'Nightly Bundles',
                'ordering': ['-date'],
            },
        ),
    ]
