# Generated by Django 5.2.5 on 2026-07-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragbot', '0010_Night_bundle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcedocument',
            name='drive_file_id',
            field=models.CharField(max_length=2048),
        ),
    ]
